### ISSUE TITLE
Create NOX.Type [CompundType] "StreetAddress"

### ISSUE THREAD

**Issue by nagykarim** [NoxOrg/Nox.Types#20]
MP-7023

**Comment by rochar** [comment]
# Additional notes:

Standard Address Contract for any service: 

- 	The standard address contract for any microservice will be driven by current [Google API definition: Validate an address  |  Address Validation API  |  Google for Developers](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.google.com%2Fmaps%2Fdocumentation%2Faddress-validation%2Frequests-validate-address%23address_validation_response&data=05%7C01%7CRicardo.Rocha%40iwgplc.com%7Ccbe939e2955f4edebd8708db7313536b%7C88155c28f750401391d38347ddb3daa7%7C0%7C0%7C638230299069950876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZNu0Qt4eumLhqEcPN%2Bqh1IuICK0EmWumYiCy%2FmXt1kw%3D&reserved=0)
-  The reason is because most of client applications  should use google to search for an address and then get all the details and store them in the microservice. 
- So Customer should use Google API on the front end previously to send the information to the, backend, service)

## Street Address Compound type, attributes to consider:

 -   StreetNumber int
 -  AddressLine1 string
 - AddressLine2 string
 - Route string
 - Locality string
 - Neighborhood string
 - AdministrativeArea1 string
 - AdministrativeArea2 string
 - PostalCode string  
 - CountryId CountryCode2
